/* rPPG engine ported from 0822loopal-cell/rppg-check.
   UI/advice/history logic is intentionally excluded. */
window.RPPGEngine = (() => {
const average=v=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
const standardDeviation=v=>{if(v.length<2)return 0;const m=average(v);return Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/v.length)};
const median=v=>{const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function createPOSSignal(r,g,b,sampleRate){const n=r.length,out=new Array(n).fill(0),weight=new Array(n).fill(0),wl=Math.max(12,Math.round(sampleRate*1.6)),step=Math.max(1,Math.round(wl/4));for(let st=0;st+wl<=n;st+=step){const en=st+wl;let mr=0,mg=0,mb=0;for(let i=st;i<en;i++){mr+=r[i];mg+=g[i];mb+=b[i]}mr/=wl;mg/=wl;mb/=wl;if(!mr||!mg||!mb)continue;const x=[],y=[];for(let i=st;i<en;i++){const rn=r[i]/mr,gn=g[i]/mg,bn=b[i]/mb;x.push(gn-bn);y.push(gn+bn-2*rn)}const sy=standardDeviation(y),alpha=sy?standardDeviation(x)/sy:0,h=x.map((v,i)=>v+alpha*y[i]),hm=average(h);for(let i=0;i<wl;i++){out[st+i]+=h[i]-hm;weight[st+i]++}}for(let i=0;i<n;i++)if(weight[i])out[i]/=weight[i];return out}
function removeBaseline(a,w){const o=[],h=Math.floor(w/2);for(let i=0;i<a.length;i++){let s=0,c=0;for(let j=Math.max(0,i-h);j<=Math.min(a.length-1,i+h);j++){s+=a[j];c++}o.push(a[i]-s/c)}return o}
const centerSignal=a=>{const m=average(a);return a.map(x=>x-m)};
function smoothSignal(a,r){return a.map((_,i)=>{let s=0,c=0;for(let j=Math.max(0,i-r);j<=Math.min(a.length-1,i+r);j++){s+=a[j];c++}return s/c})}
const applyHannWindow=a=>a.map((v,i)=>v*.5*(1-Math.cos(2*Math.PI*i/(a.length-1))));
function calculateSpectrum(samples,times,minBPM,maxBPM){const out=[],origin=times[0];for(let bpm=minBPM;bpm<=maxBPM;bpm++){const f=bpm/60;let re=0,im=0;for(let i=0;i<samples.length;i++){const t=(times[i]-origin)/1000,ang=2*Math.PI*f*t;re+=samples[i]*Math.cos(ang);im-=samples[i]*Math.sin(ang)}out.push({bpm,frequency:f,power:re*re+im*im})}return out}
function signalAmplitude(s){return Math.max(...s)-Math.min(...s)}
function refinePeakTime(s,t,i){if(i<=0||i>=s.length-1)return t[i];const y1=s[i-1],y2=s[i],y3=s[i+1],d=y1-2*y2+y3;let o=Math.abs(d)>1e-7?.5*(y1-y3)/d:0;o=Math.max(-.5,Math.min(.5,o));return o>=0?t[i]+o*(t[i+1]-t[i]):t[i]+o*(t[i]-t[i-1])}
function trackBeats(signal,times,bpm){const beats=[];if(signal.length<20)return {beatTimes:beats};const ei=60000/bpm,firstEnd=times[0]+ei*1.3;let fi=-1,fv=-Infinity;for(let i=1;i<signal.length-1;i++){if(times[i]>firstEnd)break;if(signal[i]>signal[i-1]&&signal[i]>=signal[i+1]&&signal[i]>fv){fv=signal[i];fi=i}}if(fi<0)return {beatTimes:beats};let last=refinePeakTime(signal,times,fi);beats.push(last);const amp=signalAmplitude(signal);while(true){const pred=last+ei,ss=pred-ei*.35,se=pred+ei*.35;if(ss>times[times.length-2])break;let bi=-1,bs=-Infinity;for(let i=1;i<signal.length-1;i++){if(times[i]<ss)continue;if(times[i]>se)break;if(!(signal[i]>signal[i-1]&&signal[i]>=signal[i+1]))continue;const tw=1-Math.min(Math.abs(times[i]-pred)/ei,1),score=signal[i]+tw*amp*.25;if(score>bs){bs=score;bi=i}}if(bi<0)break;const rt=refinePeakTime(signal,times,bi);if(rt-last<ei*.60)break;beats.push(rt);last=rt}return {beatTimes:beats}}
function cleanIntervals(a,bpm){const e=60000/bpm,lo=e*.70,hi=e*1.30,accepted=[];let rejected=0;a.forEach(v=>v>=lo&&v<=hi?accepted.push(v):rejected++);if(accepted.length>=5){const m=median(accepted),final=[];accepted.forEach(v=>Math.abs(v-m)/m<=.20?final.push(v):rejected++);return {accepted:final,rejected}}return {accepted,rejected}}
function calculateRMSSD(a){if(a.length<2)return null;let s=0;for(let i=1;i<a.length;i++)s+=(a[i]-a[i-1])**2;return Math.sqrt(s/(a.length-1))}
function calculateSDNN(a){if(a.length<2)return 0;const m=average(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}
function analyze(r,g,b,times){if(g.length<100)throw new Error("insufficient_samples");const duration=(times.at(-1)-times[0])/1000,sr=(times.length-1)/duration;let start=0;while(start<times.length&&times[start]<2000)start++;const rr=r.slice(start),gg=g.slice(start),bb=b.slice(start),tt=times.slice(start);let sig=createPOSSignal(rr,gg,bb,sr);sig=removeBaseline(sig,Math.max(7,Math.round(sr*1.5)));sig=centerSignal(sig);sig=smoothSignal(sig,2);const spectrum=calculateSpectrum(applyHannWindow(sig),tt,40,180);let strongest=spectrum[0];for(const p of spectrum)if(p.power>strongest.power)strongest=p;const bpm=strongest.bpm,avgPower=average(spectrum.map(p=>p.power)),qualityRatio=strongest.power/Math.max(avgPower,1e-7),beats=trackBeats(sig,tt,bpm).beatTimes,raw=[];for(let i=1;i<beats.length;i++)raw.push(beats[i]-beats[i-1]);const cleaned=cleanIntervals(raw,bpm),ints=cleaned.accepted,rej=cleaned.rejected,rejectionRatio=raw.length?rej/raw.length:1;const meanPPI=ints.length>=4?average(ints):null,sdnn=ints.length>=4?calculateSDNN(ints):null,rmssd=ints.length>=4?calculateRMSSD(ints):null;const quality=qualityRatio>=5&&ints.length>=10&&rejectionRatio<=.15?"良好":qualityRatio>=3&&ints.length>=7&&rejectionRatio<=.40?"中程度":"低い";return {hr:Math.round(bpm),frequencyPeak:bpm,meanPPI:meanPPI===null?null:Math.round(meanPPI),rmssd:rmssd===null?null:+rmssd.toFixed(1),sdnn:sdnn===null?null:+sdnn.toFixed(1),acceptedPpi:ints.length,rejectedPpi:rej,quality,qualityRatio,sampleRate:sr}}
return {analyze};
})();